DROP TABLE subscription CASCADE CONSTRAINTS;

DROP TABLE favorite CASCADE CONSTRAINTS;

DROP TABLE interest CASCADE CONSTRAINTS;

DROP TABLE historical CASCADE CONSTRAINTS;

DROP TABLE client CASCADE CONSTRAINTS;

DROP TABLE video CASCADE CONSTRAINTS;

DROP TABLE archive CASCADE CONSTRAINTS;

DROP TABLE program CASCADE CONSTRAINTS;

DROP TABLE category CASCADE CONSTRAINTS;