INSERT INTO category VALUES (1, 'Comedy', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
INSERT INTO category VALUES (2, 'Thriller', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
INSERT INTO category VALUES (3, 'Drama', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
INSERT INTO category VALUES (4, 'Romance', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
INSERT INTO category VALUES (5, 'Crime', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
INSERT INTO category VALUES (6, 'Horror', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
INSERT INTO category VALUES (7, 'Action', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
INSERT INTO category VALUES (8, 'Western', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
INSERT INTO category VALUES (9, 'Sci-Fi', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
INSERT INTO category VALUES (10, 'Adventure', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');

INSERT INTO program VALUES (1, 7, 'Breakfast of Champions', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
INSERT INTO program VALUES (2, 6, 'Eleventh Year, The (Odinnadtsatyy) ', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
INSERT INTO program VALUES (3, 10, 'Reuben, Reuben', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.');
INSERT INTO program VALUES (4, 2, 'Oblivion Island: Haruka and the Magic Mirror (Hottarake no shima - Haruka to maho no kagami)', 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
INSERT INTO program VALUES (5, 6, 'Plain Dirty (a.k.a. Briar Patch)', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
INSERT INTO program VALUES (6, 4, 'My Blueberry Nights', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
INSERT INTO program VALUES (7, 4, 'Lupin the Third: The Secret of Mamo', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
INSERT INTO program VALUES (8, 7, 'Handle with Care (a.k.a. Citizen''s Band)', 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
INSERT INTO program VALUES (9, 1, 'West Is West', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
INSERT INTO program VALUES (10, 5, 'Small Back Room, The', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.');
INSERT INTO program VALUES (11, 6, 'State Fair', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.');
INSERT INTO program VALUES (12, 2, 'Barton Fink', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.');
INSERT INTO program VALUES (13, 10, 'Who Is Killing the Great Chefs of Europe?', 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.');
INSERT INTO program VALUES (14, 2, 'Billy Madison', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
INSERT INTO program VALUES (15, 2, 'Cose da pazzi', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
INSERT INTO program VALUES (16, 9, 'Living Dead Girl, The (Morte Vivante, La)', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
INSERT INTO program VALUES (17, 8, 'No Man''s Land', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
INSERT INTO program VALUES (18, 1, 'Man Escaped, A (Un  condamné à mort s''est échappé ou Le vent souffle où il veut)', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.');
INSERT INTO program VALUES (19, 2, 'Harmagedon', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
INSERT INTO program VALUES (20, 6, 'Do You Remember Dolly Bell? (Sjecas li se, Dolly Bell)', 'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');

INSERT INTO client VALUES (1, 'srippon0', 'VchZ42336', 'Siward', 'Rippon', 'M', 'FR', 'Saaban', '5 Warrior Lane', '5207', TO_DATE('1968-09-23', 'yyyy-mm-dd'), 'srippon0@cafepress.com', 'N');
INSERT INTO client VALUES (2, 'iragborne1', 'CGFYOTgBuKx', 'Inigo', 'Ragborne', 'M', 'FR', 'São João dos Montes', '86742 Daystar Crossing', '2600-771', TO_DATE('1972-01-03', 'yyyy-mm-dd'), 'iragborne1@psu.edu', 'Y');
INSERT INTO client VALUES (3, 'kderell2', 'iCDV12ou', 'Klarrisa', 'Derell', 'F', 'FR', 'Bingerville', '53951 Dryden Terrace', NULL, TO_DATE('1975-06-22', 'yyyy-mm-dd'), 'kderell2@csmonitor.com', 'Y');
INSERT INTO client VALUES (4, 'mschaffler3', 'pMh9kZiANj4', 'Margeaux', 'Schaffler', 'F', 'DE', 'Ključ', '8558 Grover Terrace', NULL, TO_DATE('1984-06-29', 'yyyy-mm-dd'), 'mschaffler3@ustream.tv', 'Y');
INSERT INTO client VALUES (5, 'jespinoza4', '3HQl8ssig0', 'Jeanine', 'Espinoza', 'F', 'DE', 'Podgornoye', '99 Lunder Terrace', '396564', TO_DATE('1984-03-28', 'yyyy-mm-dd'), 'jespinoza4@time.com', 'N');
INSERT INTO client VALUES (6, 'tsammons5', 'aOWl0Aaw', 'Tobe', 'Sammons', 'F', 'DE', 'Ben Arous', '598 Randy Plaza', NULL, TO_DATE('2002-12-09', 'yyyy-mm-dd'), 'tsammons5@bloglovin.com', 'Y');
INSERT INTO client VALUES (7, 'abunston6', 'K8qkNMmpEGX', 'Amandi', 'Bunston', 'F', 'DE', 'Shuanghekou', '968 Badeau Road', NULL, TO_DATE('1966-06-29', 'yyyy-mm-dd'), 'abunston6@stumbleupon.com', 'N');
INSERT INTO client VALUES (8, 'gturmall7', 'e12wxf1daJ', 'Gillie', 'Turmall', 'F', 'DE', 'Tembisa', '586 Charing Cross Crossing', '1693', TO_DATE('1996-11-13', 'yyyy-mm-dd'), 'gturmall7@theguardian.com', 'N');
INSERT INTO client VALUES (9, 'mkobelt8', 'suDI81QIIhCRh', 'Mathilda', 'Kobelt', 'F', 'ID', 'Oepuah', '4416 Fallview Park', NULL, TO_DATE('2004-06-04', 'yyyy-mm-dd'), 'mkobelt8@squarespace.com', 'N');
INSERT INTO client VALUES (10, 'onevill9', 'D0KZss1z18mU', 'Ody', 'Nevill', 'M', 'EG', 'Banī Mazār', '70 Village Green Point', NULL, TO_DATE('1970-12-14', 'yyyy-mm-dd'), 'onevill9@nyu.edu', 'Y');
INSERT INTO client VALUES (11, 'oeltonea', 'UfftJxwx9supu', 'Ola', 'Eltone', 'F', 'JP', 'Nikkō', '2 Ridgeview Place', '321-1436', TO_DATE('2000-01-05', 'yyyy-mm-dd'), 'oeltonea@reverbnation.com', 'N');
INSERT INTO client VALUES (12, 'ojezardb', '3pOzqFyIsH', 'Orlando', 'Jezard', 'M', 'RU', 'Borogontsy', '6 Myrtle Lane', '678350', TO_DATE('2004-09-08', 'yyyy-mm-dd'), 'ojezardb@google.de', 'Y');
INSERT INTO client VALUES (13, 'nvandenveldec', 'QSb3W5I4BqG9', 'Norah', 'Van den Velde', 'F', 'CN', 'Qiaochong', '75266 Heath Avenue', NULL, TO_DATE('1972-10-05', 'yyyy-mm-dd'), 'nvandenveldec@dagondesign.com', 'N');
INSERT INTO client VALUES (14, 'sneighbourd', 'AckdSCpA2', 'Savina', 'Neighbour', 'F', 'FR', 'Shangma', '2191 Forster Way', NULL, TO_DATE('1996-05-15', 'yyyy-mm-dd'), 'sneighbourd@eepurl.com', 'N');
INSERT INTO client VALUES (15, 'awillwoode', 'VP0OPCwXgEVf', 'Ardyth', 'Willwood', 'F', 'FR', 'San Miguelito', '09 Birchwood Pass', NULL, TO_DATE('1999-09-13', 'yyyy-mm-dd'), 'awillwoode@biblegateway.com', 'Y');
INSERT INTO client VALUES (16, 'twyrillf', 'zSGE9NqAspX6C8r', 'Tristam', 'Wyrill', 'M', 'CN', 'Huatan', '1 Towne Road', NULL, TO_DATE('1991-09-28', 'yyyy-mm-dd'), 'twyrillf@photobucket.com', 'Y');
INSERT INTO client VALUES (17, 'dmillmoeg', 'gQ7Dea1BI9Gz', 'Dennet', 'Millmoe', 'M', 'GR', 'Perivóli', '3751 Center Pass', NULL, TO_DATE('1978-02-23', 'yyyy-mm-dd'), 'dmillmoeg@cdbaby.com', 'N');
INSERT INTO client VALUES (18, 'spartletonh', 'l5QfaqeTZM', 'Stearn', 'Partleton', 'M', 'ID', 'Lamongan', '7 Glacier Hill Hill', NULL, TO_DATE('1986-01-31', 'yyyy-mm-dd'), 'spartletonh@ibm.com', 'Y');
INSERT INTO client VALUES (19, 'massantei', '1X5OIaLV', 'Martina', 'Assante', 'F', 'DE', 'Novyye Gorki', '75 Beilfuss Court', '155101', TO_DATE('1983-06-20', 'yyyy-mm-dd'), 'massantei@mail.ru', 'Y');
INSERT INTO client VALUES (20, 'kfettiplacej', 'Hcm22sq1czp', 'Kennett', 'Fettiplace', 'M', 'RU', 'Babushkin', '96098 Ramsey Point', '671235', TO_DATE('1995-10-04', 'yyyy-mm-dd'), 'kfettiplacej@yellowbook.com', 'N');

INSERT INTO video VALUES (1, 1, '../videos/coffee.avi', 'Coffee and Cigarettes', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 98, 2017, SYSDATE - 31, SYSDATE + 8, SYSDATE + 27, 1, 'AL', '1080p', 'AVI');
INSERT INTO video VALUES (2, 1, '../videos/bonneville.mov', 'Bonneville', 'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 29, 2019, SYSDATE - 27, SYSDATE + 7, SYSDATE + 20, 1, 'JP', '720p', 'MOV');
INSERT INTO video VALUES (3, 1, '../videos/strangler.flv', 'Strangler, The', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 104, 2019, SYSDATE - 31, SYSDATE + 2, NULL, 1, 'SE', '4320p', 'FLV');
INSERT INTO video VALUES (4, 2, '../videos/madeindagenham.avi', 'Made in Dagenham', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 365, 2017, SYSDATE - 29, SYSDATE + 8, NULL, 1, 'CN', '720p', 'AVI');
INSERT INTO video VALUES (5, 2, '../videos/barnens.mov', 'Barnens ö', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 41, 2020, SYSDATE - 31, SYSDATE + 16, NULL, 1, 'PT', '480p', 'MOV');
INSERT INTO video VALUES (6, 3, '../videos/departed.avi', 'Departed, The', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 282, 2020, SYSDATE - 35, SYSDATE + 9, SYSDATE + 29, 1, 'SE', '360p', 'AVI');
INSERT INTO video VALUES (7, 4, '../videos/headoverheels.mov', 'Head Over Heels', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 341, 2019, SYSDATE - 40, SYSDATE + 2, NULL, 1, 'FR', '480p', 'MOV');
INSERT INTO video VALUES (8, 5, '../videos/toughanddeadly.mov', 'Tough and Deadly', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', 222, 2018, SYSDATE - 27, SYSDATE + 10, SYSDATE + 30, 1, 'AF', '2160p', 'MOV');
INSERT INTO video VALUES (9, 5, '../videos/manapart.avi', 'Man Apart, A', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.', 111, 2020, SYSDATE - 28, SYSDATE + 12, NULL, 1, 'PH', '2160p', 'AVI');
INSERT INTO video VALUES (10, 5, '../videos/oldschool.mov', 'Old School', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 316, 2020, SYSDATE - 45, SYSDATE + 18, NULL, 1, 'PH', '480p', 'AVI');
INSERT INTO video VALUES (11, 5, '../videos/swissfamily.avi', 'Swiss Family Robinson', 'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 115, 2015, SYSDATE - 28, SYSDATE + 9, NULL, 1, 'KW', '240p', 'AVI');
INSERT INTO video VALUES (12, 6, '../videos/catwoman.mp4', 'Catwoman', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 113, 2018, SYSDATE - 26, SYSDATE + 17, SYSDATE + 35, 1, 'CN', '4320p', 'MP4');
INSERT INTO video VALUES (13, 7, '../videos/accused.flv', 'Accused, The', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', 383, 2018, SYSDATE - 38, SYSDATE + 14, SYSDATE + 39, 1, 'PH', '720p', 'FLV');
INSERT INTO video VALUES (14, 7, '../videos/alive.avi', 'It''s Alive', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 72, 2018, SYSDATE - 29, SYSDATE + 4, NULL, 1, 'SE', '1080p', 'AVI');
INSERT INTO video VALUES (15, 8, '../videos/lookscouldkill.avi', 'If Looks Could Kill', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 174, 2019, SYSDATE - 26, SYSDATE + 10, NULL, 1, 'PL', '2160p', 'AVI');
INSERT INTO video VALUES (16, 9, '../videos/dogpark.mov', 'Dog Park', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 281, 2016, SYSDATE - 44, SYSDATE + 18, SYSDATE + 45, 1, 'CN', '1080p', 'MOV');
INSERT INTO video VALUES (17, 10, '../videos/princess.mov', 'Princess (Prinsessa)', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 175, 2020, SYSDATE - 39, SYSDATE + 14, SYSDATE + 15, 1, 'PH', '720p', 'MOV');
INSERT INTO video VALUES (18, 11, '../videos/stealpencilforme.mp4', 'Steal a Pencil for Me', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 129, 2016, SYSDATE - 35, SYSDATE + 19, SYSDATE + 37, 1, 'CN', '480p', 'MP4');
INSERT INTO video VALUES (19, 12, '../videos/louisblue.avi', 'Louie Bluie', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 348, 2019, SYSDATE - 49, SYSDATE + 24, SYSDATE + 38, 1, 'ID', '240p', 'AVI');
INSERT INTO video VALUES (20, 13, '../videos/vampire.flv', 'Vampire, The', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 366, 2019, SYSDATE - 47, SYSDATE + 17, NULL, 1, 'VN', '480p', 'FLV');
INSERT INTO video VALUES (21, 13, '../videos/afterpoends.mp4', 'After Po Ends', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 342, 2015, SYSDATE - 48, SYSDATE + 11, SYSDATE + 74, 1, 'IQ', '480p', 'MP4');
INSERT INTO video VALUES (22, 13, '../videos/vakedspur.flv', 'Naked Spur, The', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 45, 2020, SYSDATE - 53, SYSDATE + 2, SYSDATE + 49, 1, 'US', '2160p', 'FLV');
INSERT INTO video VALUES (23, 13, '../videos/steeltoes.avi', 'Steel Toes', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 85, 2018, SYSDATE - 92, SYSDATE + 14, NULL, 1, 'NI', '240p', 'AVI');
INSERT INTO video VALUES (24, 14, '../videos/stilllife.avi', 'Still Life (Sanxia haoren)', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 93, 2016, SYSDATE - 39, SYSDATE + 43, SYSDATE + 56, 1, 'PH', '4320p', 'AVI');
INSERT INTO video VALUES (25, 15, '../videos/crimeware.flv', 'Crimewave', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', 234, 2019, SYSDATE - 27, SYSDATE + 12, NULL, 1, 'CN', '1080p', 'FLV');
INSERT INTO video VALUES (26, 16, '../videos/threeresurrected.flv', 'Three Resurrected Drunkards (Kaette kita yopparai)', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 110, 2019, SYSDATE - 64, SYSDATE + 18, NULL, 1, 'FJ', '4320p', 'FLV');
INSERT INTO video VALUES (27, 16, '../videos/goodheart.mov', 'Good Heart, The', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 230, 2017, SYSDATE - 54, SYSDATE + 7, NULL, 1, 'CZ', '720p', 'MOV');
INSERT INTO video VALUES (28, 16, '../videos/bigone.avi', 'The Big One: The Great Los Angeles Earthquake', 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 352, 2019, SYSDATE - 29, SYSDATE + 2, SYSDATE + 8, 1, 'CN', '360p', 'AVI');
INSERT INTO video VALUES (29, 16, '../videos/kaksparsh.avi', 'Kaksparsh', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 299, 2020, SYSDATE - 45, SYSDATE + 27, SYSDATE + 56, 1, 'CN', '2160p', 'AVI');
INSERT INTO video VALUES (30, 17, '../videos/praythedevil.avi', 'Pray the Devil Back to Hell', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', 202, 2017, SYSDATE - 41, SYSDATE + 12, SYSDATE + 13, 1, 'ID', '240p', 'AVI');
INSERT INTO video VALUES (31, 17, '../videos/freakin.avi', 'Freakin'' Beautiful World (Sairaan kaunis maailma)', 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 173, 2020, SYSDATE - 67, SYSDATE + 2, SYSDATE + 46, 1, 'PH', '480p', 'AVI');
INSERT INTO video VALUES (32, 17, '../videos/hoodwinked.avi', 'Hoodwinked!', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 362, 2015, SYSDATE - 29, SYSDATE + 21, SYSDATE + 12, 1, 'RU', '360p', 'AVI');
INSERT INTO video VALUES (33, 18, '../videos/darkcommand.flv', 'Dark Command', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 142, 2016, SYSDATE - 65, SYSDATE + 21, SYSDATE + 42, 1, 'CZ', '720p', 'FLV');
INSERT INTO video VALUES (34, 19, '../videos/napstrike.mov', 'Nap Strike, The', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 52, 2017, SYSDATE - 32, SYSDATE + 12, NULL, 1, 'BG', '720p', 'MOV');
INSERT INTO video VALUES (35, 20, '../videos/fastlife.avi', 'Fast Life', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 311, 2015, SYSDATE - 27, SYSDATE + 9, NULL, 1, 'CN', '360p', 'AVI');
INSERT INTO video VALUES (36, 20, '../videos/cryofbanshee.mp4', 'Cry of the Banshee', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', 136, 2018, SYSDATE - 32, SYSDATE + 21, NULL, 1, 'CN', '480p', 'MP4');
INSERT INTO video VALUES (37, 20, '../videos/beautyandbeast.mp4', 'Beauty and the Beast', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 308, 2018, SYSDATE - 32, SYSDATE + 43, NULL, 1, 'MA', '2160p', 'MP4');
INSERT INTO video VALUES (38, 20, '../videos/bigsqueeze.flv', 'Big Squeeze, The', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 25, 2020, SYSDATE - 45, SYSDATE + 6, NULL, 1, 'AF', '4320p', 'FLV');
INSERT INTO video VALUES (39, 20, '../videos/memoirsinvisibleman.mov', 'Memoirs of an Invisible Man 2', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 272, 2016, SYSDATE - 61, SYSDATE + 1, NULL, 1, 'CZ', '480p', 'MOV');
INSERT INTO video VALUES (40, 20, '../videos/terumaeromae.avi', 'Terumae romae (Thermae Romae)', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 318, 2018, SYSDATE - 38, SYSDATE + 21, NULL, 1, 'RU', '4320p', 'AVI');

INSERT INTO archive VALUES (1, 1, '../videos/memoirsinvisibleman2.avi', 'Memoirs of an Invisible Man 2', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 99, 2015, SYSDATE - 87, SYSDATE - 19, NULL, 1, 'DE', '1080p', 'AVI');
INSERT INTO archive VALUES (2, 2, '../videos/gilbertgibier.mov', 'Gilbert le Gibier', 'Interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed.', 78, 2012, SYSDATE - 81, SYSDATE - 54, SYSDATE + 14, 1, 'FR', '720p', 'MOV');
INSERT INTO archive VALUES (3, 9, '../videos/strangers.flv', 'Strangers', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 104, 2018, SYSDATE - 93, SYSDATE - 64, NULL, 1, 'IT', '4320p', 'FLV');

INSERT INTO subscription VALUES (1, 6);
INSERT INTO subscription VALUES (4, 12);
INSERT INTO subscription VALUES (20, 8);
INSERT INTO subscription VALUES (11, 7);
INSERT INTO subscription VALUES (11, 18);
INSERT INTO subscription VALUES (1, 3);
INSERT INTO subscription VALUES (17, 13);
INSERT INTO subscription VALUES (18, 10);
INSERT INTO subscription VALUES (12, 7);
INSERT INTO subscription VALUES (7, 14);
INSERT INTO subscription VALUES (18, 9);
INSERT INTO subscription VALUES (12, 8);
INSERT INTO subscription VALUES (11, 8);
INSERT INTO subscription VALUES (20, 3);
INSERT INTO subscription VALUES (2, 14);
INSERT INTO subscription VALUES (12, 16);
INSERT INTO subscription VALUES (18, 2);
INSERT INTO subscription VALUES (6, 20);
INSERT INTO subscription VALUES (13, 1);
INSERT INTO subscription VALUES (17, 17);
INSERT INTO subscription VALUES (2, 12);
INSERT INTO subscription VALUES (11, 11);
INSERT INTO subscription VALUES (12, 15);
INSERT INTO subscription VALUES (16, 13);
INSERT INTO subscription VALUES (16, 11);
INSERT INTO subscription VALUES (9, 17);
INSERT INTO subscription VALUES (4, 5);
INSERT INTO subscription VALUES (7, 4);
INSERT INTO subscription VALUES (18, 11);
INSERT INTO subscription VALUES (17, 10);
INSERT INTO subscription VALUES (7, 2);
INSERT INTO subscription VALUES (1, 16);
INSERT INTO subscription VALUES (17, 9);
INSERT INTO subscription VALUES (13, 8);
INSERT INTO subscription VALUES (20, 10);
INSERT INTO subscription VALUES (14, 1);
INSERT INTO subscription VALUES (10, 19);
INSERT INTO subscription VALUES (7, 10);
INSERT INTO subscription VALUES (20, 6);
INSERT INTO subscription VALUES (17, 5);
INSERT INTO subscription VALUES (13, 12);
INSERT INTO subscription VALUES (20, 11);
INSERT INTO subscription VALUES (12, 4);
INSERT INTO subscription VALUES (10, 6);
INSERT INTO subscription VALUES (10, 5);
INSERT INTO subscription VALUES (7, 8);
INSERT INTO subscription VALUES (6, 2);
INSERT INTO subscription VALUES (4, 9);
INSERT INTO subscription VALUES (3, 20);
INSERT INTO subscription VALUES (5, 3);

INSERT INTO historical VALUES (1, 26, SYSDATE - 11);
INSERT INTO historical VALUES (13, 31, SYSDATE - 21);
INSERT INTO historical VALUES (13, 15, SYSDATE - 6);
INSERT INTO historical VALUES (6, 29, SYSDATE - 5);
INSERT INTO historical VALUES (5, 32, SYSDATE - 12);
INSERT INTO historical VALUES (20, 31, SYSDATE - 9);
INSERT INTO historical VALUES (3, 16, SYSDATE - 9);
INSERT INTO historical VALUES (4, 20, SYSDATE - 4);
INSERT INTO historical VALUES (19, 31, SYSDATE - 1);
INSERT INTO historical VALUES (15, 30, SYSDATE - 20);
INSERT INTO historical VALUES (19, 32, SYSDATE - 17);
INSERT INTO historical VALUES (14, 1, SYSDATE - 19);
INSERT INTO historical VALUES (16, 11, SYSDATE - 11);
INSERT INTO historical VALUES (19, 31, SYSDATE - 7);
INSERT INTO historical VALUES (19, 23, SYSDATE - 11);
INSERT INTO historical VALUES (4, 36, SYSDATE - 23);
INSERT INTO historical VALUES (16, 30, SYSDATE - 8);
INSERT INTO historical VALUES (18, 6, SYSDATE - 5);
INSERT INTO historical VALUES (16, 4, SYSDATE - 11);
INSERT INTO historical VALUES (10, 28, SYSDATE - 17);
INSERT INTO historical VALUES (1, 26, SYSDATE - 9);
INSERT INTO historical VALUES (4, 29, SYSDATE);
INSERT INTO historical VALUES (15, 21, SYSDATE - 15);
INSERT INTO historical VALUES (1, 16, SYSDATE - 4);
INSERT INTO historical VALUES (16, 23, SYSDATE - 2);
INSERT INTO historical VALUES (6, 2, SYSDATE - 8);
INSERT INTO historical VALUES (4, 21, SYSDATE - 18);
INSERT INTO historical VALUES (14, 8, SYSDATE - 9);
INSERT INTO historical VALUES (2, 28, SYSDATE);
INSERT INTO historical VALUES (19, 27, SYSDATE - 10);
INSERT INTO historical VALUES (11, 27, SYSDATE - 4);
INSERT INTO historical VALUES (6, 17, SYSDATE - 3);
INSERT INTO historical VALUES (8, 25, SYSDATE - 7);
INSERT INTO historical VALUES (1, 15, SYSDATE - 9);
INSERT INTO historical VALUES (3, 24, SYSDATE - 19);
INSERT INTO historical VALUES (14, 22, SYSDATE - 22);
INSERT INTO historical VALUES (20, 6, SYSDATE);
INSERT INTO historical VALUES (16, 31, SYSDATE);
INSERT INTO historical VALUES (13, 7, SYSDATE - 16);
INSERT INTO historical VALUES (3, 14, SYSDATE - 9);
INSERT INTO historical VALUES (15, 33, SYSDATE - 18);
INSERT INTO historical VALUES (1, 20, SYSDATE - 22);
INSERT INTO historical VALUES (2, 20, SYSDATE);
INSERT INTO historical VALUES (3, 20, SYSDATE);
INSERT INTO historical VALUES (4, 20, SYSDATE - 16);
INSERT INTO historical VALUES (5, 20, SYSDATE - 9);
INSERT INTO historical VALUES (6, 20, SYSDATE - 18);
INSERT INTO historical VALUES (1, 29, SYSDATE - 21);
INSERT INTO historical VALUES (2, 29, SYSDATE - 4);
INSERT INTO historical VALUES (3, 29, SYSDATE - 17);
INSERT INTO historical VALUES (4, 29, SYSDATE - 3);
INSERT INTO historical VALUES (5, 29, SYSDATE - 1);
INSERT INTO historical VALUES (6, 29, SYSDATE - 16);

INSERT INTO historical VALUES (2, 31, SYSDATE - 8);
INSERT INTO historical VALUES (2, 31, SYSDATE - 9);
INSERT INTO historical VALUES (2, 32, SYSDATE - 10);


INSERT INTO favorite VALUES (20, 18);
INSERT INTO favorite VALUES (18, 20);
INSERT INTO favorite VALUES (15, 8);
INSERT INTO favorite VALUES (17, 8);
INSERT INTO favorite VALUES (2, 16);
INSERT INTO favorite VALUES (5, 29);
INSERT INTO favorite VALUES (13, 21);
INSERT INTO favorite VALUES (13, 3);
INSERT INTO favorite VALUES (9, 15);
INSERT INTO favorite VALUES (15, 32);
INSERT INTO favorite VALUES (15, 1);
INSERT INTO favorite VALUES (19, 33);
INSERT INTO favorite VALUES (9, 33);
INSERT INTO favorite VALUES (15, 10);
INSERT INTO favorite VALUES (13, 14);
INSERT INTO favorite VALUES (20, 4);
INSERT INTO favorite VALUES (4, 25);
INSERT INTO favorite VALUES (1, 4);
INSERT INTO favorite VALUES (13, 23);
INSERT INTO favorite VALUES (4, 26);
INSERT INTO favorite VALUES (10, 28);
INSERT INTO favorite VALUES (3, 11);
INSERT INTO favorite VALUES (15, 33);
INSERT INTO favorite VALUES (9, 35);
INSERT INTO favorite VALUES (6, 15);
INSERT INTO favorite VALUES (7, 17);
INSERT INTO favorite VALUES (4, 28);
INSERT INTO favorite VALUES (3, 40);
INSERT INTO favorite VALUES (3, 4);
INSERT INTO favorite VALUES (14, 32);
INSERT INTO favorite VALUES (17, 6);
INSERT INTO favorite VALUES (9, 2);
INSERT INTO favorite VALUES (13, 1);
INSERT INTO favorite VALUES (11, 14);
INSERT INTO favorite VALUES (10, 4);
INSERT INTO favorite VALUES (19, 26);
INSERT INTO favorite VALUES (15, 27);
INSERT INTO favorite VALUES (13, 22);
INSERT INTO favorite VALUES (20, 27);
INSERT INTO favorite VALUES (9, 36);

INSERT INTO interest VALUES (1, 5);
INSERT INTO interest VALUES (12, 9);
INSERT INTO interest VALUES (4, 2);
INSERT INTO interest VALUES (9, 10);
INSERT INTO interest VALUES (6, 7);
INSERT INTO interest VALUES (13, 4);
INSERT INTO interest VALUES (20, 7);
INSERT INTO interest VALUES (16, 6);
INSERT INTO interest VALUES (18, 1);
INSERT INTO interest VALUES (9, 3);
INSERT INTO interest VALUES (9, 9);
INSERT INTO interest VALUES (14, 1);
INSERT INTO interest VALUES (7, 9);
INSERT INTO interest VALUES (2, 3);
INSERT INTO interest VALUES (6, 4);
INSERT INTO interest VALUES (3, 4);
INSERT INTO interest VALUES (1, 6);
INSERT INTO interest VALUES (12, 3);
INSERT INTO interest VALUES (19, 3);
INSERT INTO interest VALUES (4, 3);
INSERT INTO interest VALUES (5, 9);
INSERT INTO interest VALUES (15, 4);
INSERT INTO interest VALUES (15, 1);
INSERT INTO interest VALUES (1, 7);
INSERT INTO interest VALUES (9, 8);
INSERT INTO interest VALUES (3, 2);
INSERT INTO interest VALUES (15, 5);
INSERT INTO interest VALUES (19, 7);
INSERT INTO interest VALUES (3, 1);
INSERT INTO interest VALUES (6, 9);
INSERT INTO interest VALUES (14, 4);
INSERT INTO interest VALUES (8, 8);
INSERT INTO interest VALUES (10, 1);
INSERT INTO interest VALUES (14, 6);
INSERT INTO interest VALUES (6, 1);
INSERT INTO interest VALUES (16, 2);
INSERT INTO interest VALUES (5, 2);
INSERT INTO interest VALUES (19, 5);
INSERT INTO interest VALUES (6, 6);
INSERT INTO interest VALUES (18, 2);
