-- 1
WITH LATEST_VIEWS AS (
    SELECT IDVIDEO
    FROM HISTORICAL
    WHERE VIEWINGDATE > (SYSDATE - 14)
)
SELECT IDCATEGORY, COUNT(IDVIDEO)
FROM LATEST_VIEWS
         NATURAL LEFT JOIN VIDEO
         NATURAL LEFT JOIN PROGRAM
         NATURAL FULL JOIN CATEGORY
GROUP BY IDCATEGORY;

-- 2
SELECT C.IDCLIENT,
       COUNT(DISTINCT S.IDPROGRAM) AS NBSUBS,
       COUNT(DISTINCT F.IDVIDEO)   AS NBFAVS,
       COUNT(DISTINCT H.IDVIDEO)   AS NBSEEN
FROM CLIENT C
         LEFT JOIN SUBSCRIPTION S ON S.IDCLIENT = C.IDCLIENT
         LEFT JOIN FAVORITE F ON F.IDCLIENT = C.IDCLIENT
         LEFT JOIN HISTORICAL H ON C.IDCLIENT = H.IDCLIENT
GROUP BY C.IDCLIENT;

-- 3
WITH FR_CLIENTS AS (
    SELECT IDCLIENT
    FROM CLIENT
    WHERE NATIONALITY = 'FR'
),
     DE_CLIENTS AS (
         SELECT IDCLIENT
         FROM CLIENT
         WHERE NATIONALITY = 'DE'
     )
SELECT V.IDVIDEO AS VIDEO, COUNT(F.IDCLIENT) AS FR, COUNT(D.IDCLIENT) AS DE
FROM VIDEO V
         LEFT JOIN HISTORICAL H ON H.IDVIDEO = V.IDVIDEO
         LEFT JOIN FR_CLIENTS F ON F.IDCLIENT = H.IDCLIENT
         LEFT JOIN DE_CLIENTS D ON D.IDCLIENT = H.IDCLIENT
GROUP BY V.IDVIDEO
ORDER BY ABS(FR - DE);

-- 4
WITH VIDEO_VIEWS AS (
    SELECT IDVIDEO, COUNT(*) AS VIEWS
    FROM HISTORICAL
    GROUP BY IDVIDEO
)
SELECT V.IDVIDEO
FROM VIDEO V
         JOIN VIDEO_VIEWS VV ON VV.IDVIDEO = V.IDVIDEO
WHERE VV.VIEWS > (
    SELECT 2 * AVG(VIEWS)
    FROM VIDEO
             NATURAL JOIN VIDEO_VIEWS
    WHERE IDVIDEO != V.IDVIDEO
      AND IDPROGRAM = V.IDPROGRAM
    GROUP BY IDPROGRAM
);

-- 5
WITH VIDEO_PAIRS AS (
    SELECT H1.IDVIDEO AS VIDEO1, H2.IDVIDEO AS VIDEO2, COUNT(DISTINCT H1.IDCLIENT) AS NB
    FROM HISTORICAL H1
             JOIN HISTORICAL H2 ON H2.IDCLIENT = H1.IDCLIENT
    WHERE H1.IDVIDEO < H2.IDVIDEO
    GROUP BY H1.IDVIDEO, H2.IDVIDEO
    ORDER BY NB DESC
)
SELECT VIDEO1, VIDEO2
FROM VIDEO_PAIRS
WHERE ROWNUM <= 10;